web/app/views/company.py
import io
from zoneinfo import ZoneInfo
from datetime import datetime

from flask import (
    jsonify,
    Blueprint,
    abort,
    request,
    send_file,
    flash,
    redirect,
    url_for,
)
from flask_login import login_required, current_user

from app import models as m
from app.controllers import create_company_billing_report
from app.logger import logger

from .utils import has_access_to_company


company_blueprint = Blueprint("company_blueprint", __name__, url_prefix="/company")


@company_blueprint.route("/<int:company_id>/sftp_data", methods=["GET"])
@login_required
def company_sftp_data(company_id: int):
    """Returns company sftp data as JSON

    Args:
        company_id (int): company id

    Returns:
        JSON: company sftp data
    """
    company: m.Company = m.Company.query.filter_by(id=company_id).first()

    if not company:
        logger.error("Company with id [{}] not found", company_id)
        abort(404, "Company not found.")

    # Check if user has access to company information
    if not has_access_to_company(current_user, company):
        logger.error(
            "User [{}] with access level [{}] tried to access company [{}] information",
            current_user.username,
            current_user.permission.value,
            company.name,
        )
        abort(403, "You don't have access to this company information.")

    logger.info("Sending sftp data of company {}", company.name)
    return (
        jsonify(
            company_sftp_username=company.default_sftp_username,
            company_sftp_password=company.default_sftp_password,
        ),
        200,
    )


@company_blueprint.route("/<int:company_id>/locations", methods=["GET"])
@login_required
def company_locations_list(company_id: int):
    """Returns company locations (id and name) as JSON

    Args:
        company_id (int): company id

    Returns:
        JSON: company locations
    """
    company: m.Company = m.Company.query.filter_by(id=company_id).first()

    if not company:
        logger.error("Company with id [{}] not found", company_id)
        abort(404, "Company not found.")

    # Check if user has access to company information
    if not has_access_to_company(current_user, company):
        abort(403, "You don't have access to this company locations information.")

    # If user has global access or associated with company, return all locations
    match current_user.permission:
        case m.UserPermissionLevel.GLOBAL | m.UserPermissionLevel.COMPANY:
            locations = (
                m.Location.query.filter_by(company_id=company.id)
                .order_by(m.Location.name)
                .all()
            )
        case m.UserPermissionLevel.LOCATION_GROUP:
            locations = current_user.location_group[0].locations
        case m.UserPermissionLevel.LOCATION:
            locations = current_user.location
        case _:
            locations = []

    res = [(location.id, location.name) for location in locations]

    return jsonify(locations=res), 200


@company_blueprint.route("/<int:company_id>/locations-for-groups", methods=["GET"])
@login_required
def company_locations_for_groups(company_id: int):
    """
    Returns company locations (id and name) as JSON
    Returns only locations that are not associated with any group

    Args:
        company_id (int): company id

    Returns:
        JSON: company locations
    """
    # Check if user has access to information
    if (
        current_user.permission != m.UserPermissionLevel.GLOBAL
        or current_user.role != m.UserRole.ADMIN
    ):
        abort(403, "You don't have access to this information.")

    # Find all company locations that are not associated with any group
    locations = m.Location.query.filter_by(company_id=company_id).all()

    group_id = request.args.get("group_id")

    if group_id:
        res = [
            (location.id, location.name)
            for location in locations
            if not location.group or location.group[0].id == int(group_id)
        ]
    else:
        res = [
            (location.id, location.name) for location in locations if not location.group
        ]

    return jsonify(locations=res), 200


@company_blueprint.route("/<int:company_id>/location-groups", methods=["GET"])
@login_required
def company_location_groups(company_id: int):
    """
    Returns company location groups (id and name) as JSON

    Args:
        company_id (int): company id

    Returns:
        JSON: company location groups
    """
    # Check if user has access to information
    if (
        current_user.permission.value
        not in [m.UserPermissionLevel.GLOBAL.value, m.UserPermissionLevel.COMPANY.value]
        or current_user.role != m.UserRole.ADMIN
    ):
        abort(403, "You don't have access to this information.")

    # Find all company location groups
    location_groups = m.LocationGroup.query.filter_by(company_id=company_id).all()
    res = [(group.id, group.name) for group in location_groups]

    return jsonify(location_groups=res), 200


@company_blueprint.route("/<int:company_id>/billing-report", methods=["GET"])
@login_required
def company_billing_report(company_id: int):
    """Generates billing report for company and returns it as .xlsx file

    Args:
        company_id (int): company id

    Returns:
        Response: billing report as .xlsx file
    """
    # Only global users can access this information
    if current_user.permission != m.UserPermissionLevel.GLOBAL:
        logger.error(
            "User {} tried to generate billing report for company {}",
            current_user.username,
            company_id,
        )
        abort(403, "You don't have access to this information.")

    # We recognize these dates as EST timezone
    from_date: datetime | None = request.args.get(
        "from_date",
        default=None,
        type=lambda date_string: datetime.strptime(date_string, "%Y-%m-%d").replace(
            tzinfo=ZoneInfo("America/New_York")
        ),
    )
    to_date: datetime | None = request.args.get(
        "to_date",
        default=None,
        type=lambda date_string: datetime.strptime(date_string, "%Y-%m-%d").replace(
            tzinfo=ZoneInfo("America/New_York")
        ),
    )

    if not from_date or not to_date:
        logger.error(f"Incorrect date format to generate billing report {company_id}")
        abort(400, "Invalid date format.")

    company: m.Company = m.Company.query.with_deleted().filter_by(id=company_id).first()

    if not company:
        logger.error(f"Company with id {company_id} not found")
        abort(404, "Company not found.")

    # Generate billing report for company
    report: io.BytesIO = create_company_billing_report(company, from_date, to_date)

    return send_file(
        report,
        mimetype="application/ms-excel",
        as_attachment=True,
        download_name=f"Report_{company.name}.xlsx",
    )


@company_blueprint.route("/<int:company_id>/activation", methods=["GET"])
@login_required
def company_activation(company_id: int):
    """
    Activates or deactivates company

    Args:
        company_id (int): company id
    """
    # Check if the user is global admin
    if (
        current_user.permission != m.UserPermissionLevel.GLOBAL
        or current_user.role != m.UserRole.ADMIN
    ):
        logger.error(
            "User {} tried to activate/deactivate company {}",
            current_user.username,
            company_id,
        )

        abort(403, "You don't have access to this option.")

    company: m.Company = m.Company.query.filter_by(id=company_id).first()

    # Check if company exists
    if not company:
        logger.error(f"Company with id {company_id} not found")
        abort(404, "Company not found.")

    should_activate = request.args.get(
        "activate", type=lambda value: True if value == "True" else False
    )

    # Check if activation parameter is provided
    if should_activate is None:
        logger.error("No activation parameter provided")
        flash("No activation parameter provided.", "danger")

        return redirect(url_for("company.edit_view", id=company_id))

    if should_activate:
        company.activate(commit=True)
        flash(f"Company {company.name} was activated successfully.", "success")
    else:
        company.deactivate(commit=True)
        flash(f"Company {company.name} was deactivated successfully.", "success")

    return redirect(url_for("company.edit_view", id=company_id))


@company_blueprint.route("/<int:company_id>/<int:location_id>", methods=["GET"])
@login_required
def company_locations_list_exclude_selected_location(company_id: int, location_id: int):
    """Returns company locations (id and name) as JSON

    Args:
        company_id (int): company id
        location_id (int): location id

    Returns:
        JSON: company locations
    """
    company: m.Company = m.Company.query.filter_by(id=company_id).first()

    if not company:
        logger.error("Company with id [{}] not found", company_id)
        abort(404, "Company not found.")

    # Check if user has access to company information
    if not has_access_to_company(current_user, company):
        abort(403, "You don't have access to this company locations information.")

    # If user has global access or associated with company, return all locations
    match current_user.permission:
        case m.UserPermissionLevel.GLOBAL | m.UserPermissionLevel.COMPANY:
            locations = (
                m.Location.query.filter(
                    (m.Location.company_id == company.id)
                    & (
                        m.Location.id != location_id
                    )  # Виключити локацію за її ідентифікатором
                )
                .order_by(m.Location.name)
                .all()
            )
        case m.UserPermissionLevel.LOCATION_GROUP:
            locations = current_user.location_group[0].locations

web/app/views/main.py
from flask import render_template, Blueprint
from sqlalchemy import or_
from sqlalchemy.orm import Query
from flask_login import login_required, current_user

from app.models import (
    Location,
    LocationStatus,
    Computer,
    ComputerStatus,
    DeviceRole,
    User,
    UserPermissionLevel,
)
from app.utils import get_percentage

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
@login_required
def index():
    viewer: User = User.query.filter_by(id=current_user.id).first()

    match viewer.permission:
        case UserPermissionLevel.GLOBAL:
            total_locations_query: Query = Location.query.filter(
                Location.computers_per_location > 0
            )
            total_computers_query: Query = Computer.query
        case UserPermissionLevel.COMPANY:
            total_locations_query: Query = Location.query.filter(
                Location.company_id == viewer.company_id,
                Location.computers_per_location > 0,
            )
            total_computers_query = Computer.query.filter(
                or_(
                    Computer.company_id == viewer.company_id,
                    Computer.location_id.in_(
                        [loc.id for loc in total_locations_query.all()]
                    ),
                )
            )
        case UserPermissionLevel.LOCATION_GROUP:
            location_ids = [loc.id for loc in viewer.location_group[0].locations]
            total_locations_query: Query = Location.query.filter(
                Location.id.in_(location_ids),
                Location.computers_per_location > 0,
            )
            total_computers_query: Query = Computer.query.filter(
                Computer.location_id.in_(location_ids),
            )
        case UserPermissionLevel.LOCATION:
            total_locations_query: Query = Location.query.filter(
                Location.id == viewer.location[0].id,
                Location.computers_per_location > 0,
            )
            total_computers_query = Computer.query.filter(
                Computer.location_id == viewer.location[0].id
            )

    # Count locations information
    locations_offline_query: Query = total_locations_query.filter(
        Location.status == LocationStatus.OFFLINE,
        Location.activated.is_(True),
    )
    locations_offline_perc: float = get_percentage(
        total_locations_query.filter_by(activated=True).all(),
        locations_offline_query.all(),
    )

    locations_online_query: Query = total_locations_query.filter(
        Location.status == LocationStatus.ONLINE,
        Location.activated.is_(True),
    )
    locations_online_perc: float = get_percentage(
        total_locations_query.filter_by(activated=True).all(),
        locations_online_query.all(),
    )

    locations_primary_offline_query: Query = total_locations_query.filter(
        Location.status == LocationStatus.ONLINE_PRIMARY_OFFLINE,
        Location.activated.is_(True),
    )
    locations_primary_offline_perc: float = get_percentage(
        total_locations_query.filter_by(activated=True).all(),
        locations_primary_offline_query.all(),
    )

    # Overall computers information
    computers_online_query: Query = total_computers_query.filter(
        Computer.status == ComputerStatus.ONLINE.value
    )
    computers_online_perc: float = get_percentage(
        total_computers_query.filter_by(activated=True).all(),
        computers_online_query.all(),
    )

    computers_offline_query: Query = total_computers_query.filter(
        Computer.status != ComputerStatus.ONLINE.value,
        Computer.status != ComputerStatus.NOT_ACTIVATED.value.replace("_", " "),
    )
    computers_offline_perc: float = get_percentage(
        total_computers_query.filter_by(activated=True).all(),
        computers_offline_query.all(),
    )

    # Primary computers information
    activated_primary_computers: list[Computer] = total_computers_query.filter(
        Computer.activated.is_(True), Computer.device_role == DeviceRole.PRIMARY
    ).all()
    primary_online_query: Query = total_computers_query.filter(
        Computer.device_role == DeviceRole.PRIMARY,
        Computer.status == ComputerStatus.ONLINE.value,
    )
    primary_online_perc: float = get_percentage(
        activated_primary_computers, primary_online_query.all()
    )

    primary_offline_query: Query = total_computers_query.filter(
        Computer.device_role == DeviceRole.PRIMARY,
        Computer.status != ComputerStatus.ONLINE.value,
        Computer.status != ComputerStatus.NOT_ACTIVATED.value.replace("_", " "),
    )
    primary_offline_perc: float = get_percentage(
        activated_primary_computers, primary_offline_query.all()
    )

    # Alternate computers information
    activated_alternate_computers: list[Computer] = total_computers_query.filter(
        Computer.activated.is_(True), Computer.device_role == DeviceRole.ALTERNATE
    ).all()
    alternate_online_query: Query = total_computers_query.filter(
        Computer.device_role == DeviceRole.ALTERNATE,
        Computer.status == ComputerStatus.ONLINE.value,
    )
    alternate_online_perc: float = get_percentage(
        activated_alternate_computers, alternate_online_query.all()
    )

    alternate_offline_query: Query = total_computers_query.filter(
        Computer.device_role == DeviceRole.ALTERNATE,
        Computer.status != ComputerStatus.ONLINE.value,
        Computer.status != ComputerStatus.NOT_ACTIVATED.value.replace("_", " "),
    )
    alternate_offline_perc: float = get_percentage(
        activated_alternate_computers, alternate_offline_query.all()
    )

    return render_template(
        "index.html",
        total_locations=total_locations_query.count(),
        total_computers=total_computers_query.count(),
        locations_offline=locations_offline_query.count(),
        locations_offline_perc=locations_offline_perc,
        locations_online=locations_online_query.count(),
        locations_online_perc=locations_online_perc,
        locations_primary_offline=locations_primary_offline_query.count(),
        locations_primary_offline_perc=locations_primary_offline_perc,
        computers_online=computers_online_query.count(),
        computers_online_perc=computers_online_perc,
        computers_offline=computers_offline_query.count(),
        computers_offline_perc=computers_offline_perc,
        primary_online=primary_online_query.count(),
        primary_online_perc=primary_online_perc,
        primary_offline=primary_offline_query.count(),
        primary_offline_perc=primary_offline_perc,
        alternate_online=alternate_online_query.count(),
        alternate_online_perc=alternate_online_perc,
        alternate_offline=alternate_offline_query.count(),
        alternate_offline_perc=alternate_offline_perc,
    )

web/app/templates/_macros.html
<!-- Put your reusable template code into macros here -->

web/app/templates/error.html
{% extends "base.html" %}

{% block flash_messages %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="d-flex align-items-center alert alert-info alert-dismissable">
      {% for message in messages %}
        <div>{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
      {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{% endblock %}

{% block content %}
<!-- 404 Error Text -->
<div class="text-center">
  <div class="error mx-auto" data-text="404">{{ error.code }}</div>
  <p class="lead text-gray-800 mb-5">{{ error.name }}</p>
  <p class="text-gray-500 mb-0">{{ error.description }}</p>
  <a href="{{ url_for('main.index') }}">&larr; Back to Dashboard</a>
</div>
{% endblock %}

{% block sidebar_toggle %}
{% endblock %}

{% block bootstrap_core %}
  <!-- This if statement is required to avoid double import if jQuery. Otherwise some funtions brake -->
  <script src="{{ url_for('static', filename='/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='/vendor/jquery/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='/vendor/jquery/popper.min.js.map') }}"></script>
{% endblock %}

web/app/templates/import-admin-create-to-dashboard.html
{% import '/admin/model/create.html' as admin_create with context %}
{% extends 'base.html' %}

{% block content %}
{{admin_create}}
{% endblock %}

web/app/templates/import-admin-edit-to-dashboard.html
{% import '/admin/model/edit.html' as admin_edit with context %} {% extends
'base.html' %} {% block content %} {% if "/admin/user/" in return_url %}
<!-- Change emails receiving -->
<div class="d-flex justify-content-end w-100 mb-3">
  <button
    type="button"
    class="btn btn-primary mr-2"
    data-toggle="modal"
    data-target="#notification-settings-modal"
  >
    Notifications settings
  </button>

  <!-- Modal -->
  <div
    class="modal fade"
    id="notification-settings-modal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="notification-settings-modal-label"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="notification-settings-modal-label">
            Notifications settings
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form
            id="notification-settings-form"
            action="/notification-settings"
            method="post"
          >
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="user_id" value="{{ model.id }}" />
            <input type="hidden" name="user_email" value="{{ model.email }}" />
            <div class="form-group">
              <label class="text-gray-900" for="user-email-input"
                >{{model.email}}</label
              >
            </div>
            <div class="form-group">
              <div class="col-lg-10">
                <div class="input-group">
                  <span class="input-group-addon">
                    <!-- prettier-ignore -->
                    <input
                      type="checkbox"
                      name="receive_alert_emails"
                      aria-label="Receive Alerts emails"
                      {% if model.receive_alert_emails %}checked{% endif %}
                    />
                  </span>
                  <label class="text-gray-900 ml-3" for="receive-alert-emails"
                    >Receive Alerts emails</label
                  >
                </div>
              </div>
            </div>
            <!-- Summaries emails -->
            <div class="form-group">
              <div class="col-lg-10">
                <div class="input-group">
                  <span class="input-group-addon">
                    <!-- prettier-ignore -->
                    <input
                      type="checkbox"
                      name="receive_summaries_emails"
                      aria-label="Receive Summaries emails"
                      {% if model.receive_summaries_emails %}checked{% endif %}
                    />
                  </span>
                  <!-- prettier-ignore -->
                  <label class="text-gray-900 ml-3" for="receive-summaries-emails">Receive Summaries emails</label>
                </div>
              </div>
            </div>
            <!-- Device test emails -->
            <div class="form-group">
              <div class="col-lg-10">
                <div class="input-group">
                  <span class="input-group-addon">
                    <!-- prettier-ignore -->
                    <input
                      type="checkbox"
                      name="receive_device_test_emails"
                      aria-label="Receive Device Test emails"
                      {% if model.receive_device_test_emails %}checked{% endif %}
                    />
                  </span>
                  <!-- prettier-ignore -->
                  <label class="text-gray-900 ml-3" for="receive-device-test-emails">Receive Device Test emails</label>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
          <button
            type="submit"
            form="notification-settings-form"
            class="btn btn-primary"
          >
            Save
          </button>
        </div>
      </div>
    </div>
  </div>
  <button
    type="button"
    class="btn btn-primary"
    data-toggle="modal"
    data-target="#change-password-modal"
  >
    Change password
  </button>

  <!-- Modal -->
  <div
    class="modal fade"
    id="change-password-modal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="change-password-modal-label"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="change-password-modal-label">
            Change Password
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form
            id="change-password-form"
            action="/change-password"
            method="post"
          >
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="user_id" value="{{ model.id }}" />
            <div class="form-group">
              <label class="text-gray-900" for="new-password-input"
                >New password:</label
              >
              <div class="d-flex align-items-center">
                <input
                  id="new-password-input"
                  name="new_password"
                  type="password"
                  class="form-control mr-2"
                  placeholder="Enter new password"
                />
                <a
                  id="show-new-password"
                  type="button"
                  class="fas fa-eye"
                  onclick="showPassword(event, 'hide-new-password')"
                ></a>
                <a
                  hidden
                  id="hide-new-password"
                  type="button"
                  onclick="hidePassword(event, 'show-new-password')"
                  class="fas fa-eye-slash"
                ></a>
              </div>
            </div>

            <div class="form-group">
              <label class="text-gray-900" for="confirm-new-password-input"
                >Confirm password:</label
              >
              <div class="d-flex align-items-center">
                <input
                  id="confirm-new-password-input"
                  name="confirm_new_password"
                  type="password"
                  class="form-control mr-2"
                  placeholder="Confirm password"
                />
                <a
                  id="show-confirm-password"
                  type="button"
                  class="fas fa-eye"
                  onclick="showPassword(event, 'hide-confirm-password')"
                ></a>
                <a
                  hidden
                  id="hide-confirm-password"
                  type="button"
                  onclick="hidePassword(event, 'show-confirm-password')"
                  class="fas fa-eye-slash"
                ></a>
              </div>
              <p
                hidden
                id="passwords-not-equal-hint"
                class="text-danger text-xs"
              ></p>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
          <button
            type="submit"
            form="change-password-form"
            class="btn btn-primary"
          >
            Save
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
{% elif "/admin/company/" in return_url %}
<div class="d-flex justify-content-end w-100 mb-3">
  <button
    type="button"
    class="btn btn-primary"
    data-toggle="modal"
    data-target="#activation-company-modal"
  >
    {% if model.activated %} Deactivate {% else %} Activate {% endif %}
  </button>

  <!-- Modal -->
  <div
    class="modal fade"
    id="activation-company-modal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="activation-company-modal-label"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="activation-company-modal-label">
            {% if model.activated %} Deactivate {% else %} Activate {% endif %}
            company {{ model.name }}
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <span
            >Are you sure that you want to {{ "deactivate" if model.activated
            else "activate" }} company {{ model.name }}?</span
          >
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
          <a
            type="button"
            href="{{ url_for('company_blueprint.company_activation', company_id=model.id) }}?activate={{ False if model.activated else True }}"
            class="btn btn-primary"
            >Confirm</a
          >
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %} {{admin_edit}} {% endblock %} {% block scripts %}
<script src="{{ url_for('static', filename='js/user.js')}}"></script>
{% endblock %}

web/app/templates/import-admin-list-to-dashboard.html
{% import '/admin/list.html' as admin_list with context %}
{% extends 'base.html' %}

{% block content %}
{{admin_list}}
{% endblock %}

web/app/templates/import-company_location-to-dashboard.html
{% import 'company_location_list.html' as company_location_list with context %}
{% extends 'base.html' %}

{% block content %}
{{company_location_list}}
{% endblock %}

web/app/templates/import-computer-to-dashboard.html
{% import 'computer_list.html' as computer_list with context %}
{% extends 'base.html' %}

{% block content %}
{{computer_list}}
{% endblock %}

web/app/templates/import-edit-computer.html
<!-- prettier-ignore -->
{% import 'custom-edit-computer.html' as edit_computer with context %}
{% extends 'base.html' %}

{% block content %}
{{edit_computer}}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/add_loc_selector.js') }}"></script>
{% endblock %}

web/app/templates/location-groups-edit.html
{% import '/admin/model/edit.html' as admin_edit with context %}
{% extends 'base.html' %}

{% block content %}
    {{admin_edit}}
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/location-groups.js') }}" defer></script>
{% endblock %}