web/app/models/system_log.py
import enum
from datetime import datetime

from sqlalchemy import Enum
from sqlalchemy.orm import relationship

from app import db
from app.models.utils import ModelMixin


class SystemLogType(enum.Enum):
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"

    COMPUTER_CREATED = "COMPUTER_CREATED"
    COMPUTER_UPDATED = "COMPUTER_UPDATED"
    COMPUTER_DELETED = "COMPUTER_DELETED"

    COMPANY_CREATED = "COMPANY_CREATED"
    COMPANY_UPDATED = "COMPANY_UPDATED"
    COMPANY_DELETED = "COMPANY_DELETED"

    LOCATION_CREATED = "LOCATION_CREATED"
    LOCATION_UPDATED = "LOCATION_UPDATED"
    LOCATION_DELETED = "LOCATION_DELETED"


class SystemLog(db.Model, ModelMixin):
    __tablename__ = "system_logs"

    id = db.Column(db.Integer, primary_key=True)

    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    log_type = db.Column(Enum(SystemLogType), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    object_id = db.Column(db.Integer, nullable=False)
    object_name = db.Column(db.String(128), nullable=False)
    object_url = db.Column(db.String(256), nullable=False)

    created_by = relationship("User", lazy="select")

    def __repr__(self):
        return f"<{self.id}:{self.log_type} at {self.created_at}>"

web/app/controllers/system_log.py
from flask import url_for

from app.models import (
    SystemLogType,
    SystemLog,
    User,
    Computer,
    Company,
    Location,
)
from app.logger import logger


def create_system_log(
    log_type: SystemLogType,
    event_object: User | Computer | Company | Location,
    created_by: User | None,
):
    """Create new system log.
    To system logs we include: create, update, delete operations with users, computers, companies, locations

    Args:
        log_type (m.SystemLogType): the type of system log
        event_object (m.User | m.Computer | m.Company | m.Location):
        the object that was created/updated/deleted
        created_by (m.User): user who did this action
    """

    # URL to object edit view
    object_type = log_type.value.split("_")[0].lower()
    object_url = url_for(f"{object_type}.edit_view", id=event_object.id)

    # Object name
    if isinstance(event_object, User):
        object_name = event_object.username
    elif isinstance(event_object, Computer):
        object_name = event_object.computer_name
    else:
        object_name = event_object.name

    new_log = SystemLog(
        log_type=log_type,
        object_id=event_object.id,
        object_name=object_name,
        object_url=object_url,
        created_by_id=created_by.id if created_by else None,
    )

    new_log.save()

    logger.debug("New system log created: {}", new_log)

web/app/views/info.py
from datetime import datetime, timedelta

from flask import Blueprint, abort, current_app, render_template, request
from flask_login import current_user, login_required

from app import db
from app import models as m
from app.controllers import backup_log_on_request_to_view, create_pagination
from config import BaseConfig as CFG

from .utils import has_access_to_company, has_access_to_computer, has_access_to_location

info_blueprint = Blueprint("info", __name__, url_prefix="/info")


@info_blueprint.route("/computer/<int:computer_id>", methods=["GET"])
@login_required
def computer_info(computer_id):
    # Query params from computers list page for "Go back" button
    LOCAL_PARAMS_NAMES = ["chart_days", "per_page", "q", "page"]
    computers_list_params = []
    for arg_name, arg_value in request.args.items():
        if arg_name not in LOCAL_PARAMS_NAMES:
            computers_list_params.append(f"{arg_name}={arg_value}")

    computers_search_params = "&".join(computers_list_params)

    computer = m.Computer.query.filter_by(id=computer_id).first_or_404()

    # Check if user has access to computer information
    if not has_access_to_computer(current_user, computer):
        abort(403, "You don't have access to this computer information.")

    # Update the last computer log information
    if computer.logs_enabled:
        backup_log_on_request_to_view(computer)

    # Paginated logs for table
    computer_logs_query = m.BackupLog.query.filter(
        m.BackupLog.computer_id == computer_id,
        m.BackupLog.end_time >= datetime.utcnow() - timedelta(days=90),
    )

    last_log = computer_logs_query.order_by(m.BackupLog.start_time.desc()).first()

    per_page = request.args.get("per_page", 25, type=int)
    pagination = create_pagination(
        total=m.count(computer_logs_query), page_size=per_page
    )

    # Logs object that will be used for table
    logs = (
        db.session.execute(
            computer_logs_query.order_by(m.BackupLog.start_time.desc())
            .limit(pagination.per_page)
            .offset(pagination.skip)
        )
        .scalars()
        .all()
    )

    # Logs information for chart
    chart_days = request.args.get("chart_days", 7, type=int)

    logs_for_chart = (
        m.BackupLog.query.filter(
            m.BackupLog.computer_id == computer_id,
            m.BackupLog.end_time >= datetime.utcnow() - timedelta(days=chart_days),
        )
        .order_by(m.BackupLog.start_time.asc())
        .all()
    )

    # List objects with different data for chart.
    labels = []
    notes = []
    chart_green_data = []
    chart_yellow_data = []
    chart_red_data = []

    if logs_for_chart:
        # Set the start time for the chart (eastern time - chart_days)
        log_time = CFG.offset_to_est(
            datetime.utcnow().replace(minute=0, second=0, microsecond=0), True
        ) - timedelta(days=chart_days)
        log_to_use_index = 0

        current_log_type = None

        # Fill all the list objects with data for every hour
        while log_time < CFG.offset_to_est(datetime.utcnow(), True):
            labels.append(log_time)
            notes.append(logs_for_chart[log_to_use_index].notes)

            # Check if the current log_time is in the range of the current log
            if (
                log_time < logs_for_chart[log_to_use_index].est_start_time
                or log_time > logs_for_chart[log_to_use_index].est_end_time
            ):
                current_log_type = None
            elif not logs_for_chart[log_to_use_index].error:
                current_log_type = "green"
            elif (
                logs_for_chart[log_to_use_index].error
                == "Longer than 1 hour without a backup"
            ):
                current_log_type = "yellow"
            else:
                current_log_type = "red"

            chart_green_data.append(1 if current_log_type == "green" else None)
            chart_yellow_data.append(1 if current_log_type == "yellow" else None)
            chart_red_data.append(1 if current_log_type == "red" else None)

            log_time += timedelta(hours=1)

            if (
                log_time > logs_for_chart[log_to_use_index].est_end_time
                and (log_to_use_index + 1) <= len(logs_for_chart) - 1
            ):
                log_to_use_index += 1

    return render_template(
        "info/computer.html",
        computer=computer,
        last_log=last_log,
        logs=logs,
        page=pagination,
        chart_days=chart_days,
        labels=labels,
        chart_notes=notes,
        chart_green_data=chart_green_data,
        chart_yellow_data=chart_yellow_data,
        chart_red_data=chart_red_data,
        computers_search_params=computers_search_params,
    )


@info_blueprint.route("/system-log", methods=["GET"])
@login_required
def system_log_info():
    # This page is available only for Global admin users
    if (
        current_user.permission != m.UserPermissionLevel.GLOBAL
        or current_user.role != m.UserRole.ADMIN
    ):
        abort(403, "You don't have permission to access this page.")

    LOGS_TYPES = ["All", "Computer", "User", "Company", "Location"]

    logs_type = request.args.get("type", "All", type=str)
    days = request.args.get("days", 30, type=int)
    per_page = request.args.get("per_page", 25, type=int)
    q = request.args.get("q", type=str, default=None)

    system_logs_query = m.SystemLog.query.filter(
        m.SystemLog.created_at >= datetime.utcnow() - timedelta(days=days),
    )

    if logs_type not in LOGS_TYPES:
        logs_type = "All"

    # Filter query by some specific log type
    if logs_type == "All":
        pass
    elif logs_type == "Computer":
        system_logs_query = system_logs_query.filter(
            (m.SystemLog.log_type == m.SystemLogType.COMPUTER_CREATED)
            | (m.SystemLog.log_type == m.SystemLogType.COMPUTER_UPDATED)
            | (m.SystemLog.log_type == m.SystemLogType.COMPUTER_DELETED)
        )
    elif logs_type == "User":
        system_logs_query = system_logs_query.filter(
            (m.SystemLog.log_type == m.SystemLogType.USER_CREATED)
            | (m.SystemLog.log_type == m.SystemLogType.USER_UPDATED)
            | (m.SystemLog.log_type == m.SystemLogType.USER_DELETED)
        )
    elif logs_type == "Company":
        system_logs_query = system_logs_query.filter(
            (m.SystemLog.log_type == m.SystemLogType.COMPANY_CREATED)
            | (m.SystemLog.log_type == m.SystemLogType.COMPANY_UPDATED)
            | (m.SystemLog.log_type == m.SystemLogType.COMPANY_DELETED)
        )
    elif logs_type == "Location":
        system_logs_query = system_logs_query.filter(
            (m.SystemLog.log_type == m.SystemLogType.LOCATION_CREATED)
            | (m.SystemLog.log_type == m.SystemLogType.LOCATION_UPDATED)
            | (m.SystemLog.log_type == m.SystemLogType.LOCATION_DELETED)
        )

    # Filter query by search query
    if q:
        system_logs_query = system_logs_query.join(
            m.SystemLog.created_by, aliased=True
        ).filter(
            (m.SystemLog.object_name.ilike(f"%{q}%"))
            | (m.User.username.ilike(f"%{q}%"))
        )

    pagination = create_pagination(total=m.count(system_logs_query), page_size=per_page)

    system_logs = (
        db.session.execute(
            system_logs_query.order_by(m.SystemLog.created_at.desc())
            .limit(pagination.per_page)
            .offset(pagination.skip)
        )
        .scalars()
        .all()
    )

    pcc_daily_requests_limit: int = int(current_app.config["PCC_DAILY_QUOTA_LIMIT"])
    pcc_daily_requests_count: m.PCCDailyRequest | None = m.PCCDailyRequest.query.filter(
        m.PCCDailyRequest.reset_time >= datetime.utcnow()
    ).first()
    usage_percent = (
        int(pcc_daily_requests_count.requests_count / pcc_daily_requests_limit * 100)
        if pcc_daily_requests_count
        else 0
    )

    return render_template(
        "info/system_log.html",
        system_logs=system_logs,
        page=pagination,
        days=days,
        current_logs_type=logs_type,
        possible_logs_types=LOGS_TYPES,
        daily_limit=pcc_daily_requests_limit,
        current_requests_count=pcc_daily_requests_count,
        usage_percent=usage_percent,
    )


@info_blueprint.route("/location/<int:location_id>", methods=["GET"])
@login_required
def location_info(location_id):
    location = m.Location.query.filter_by(id=location_id).first_or_404()

    # Check if user has access to location information
    if not has_access_to_location(current_user, location):
        abort(403, "You don't have access to this location information.")

    return render_template(
        "info/location.html",
        location=location,
        computers=location.computers,
    )


@info_blueprint.route("/company/<int:company_id>", methods=["GET"])
@login_required
def company_info(company_id):
    company = m.Company.query.filter_by(id=company_id).first_or_404()

    # Check if user has access to company information
    if not has_access_to_company(current_user, company):
        abort(403, "You don't have access to this company information.")

    # get locations online and offline and in percentages

    return render_template(
        "info/company.html",
        company=company,
    )

web/app/views/location.py
from flask import jsonify, Blueprint, abort
from flask_login import login_required, current_user

from app import models as m

from app.logger import logger

from .utils import has_access_to_location


location_blueprint = Blueprint("location_blueprint", __name__, url_prefix="/location")


@location_blueprint.route("/<int:location_id>/sftp_data", methods=["GET"])
@login_required
def location_sftp_data(location_id: int):
    """Returns location sftp data as JSON

    Args:
        location_id (int): location id

    Returns:
        JSON: location sftp data
    """
    location: m.Location = m.Location.query.filter_by(id=location_id).first()

    if not location:
        logger.error("Location with id [{}] not found", location_id)
        abort(404, "Location not found.")

    # Check if user has access to location information
    if not has_access_to_location(current_user, location):
        abort(403, "You don't have access to this location information.")

    logger.info("Sending sftp data of location {}", location.name)
    return (
        jsonify(
            default_sftp_path=location.default_sftp_path,
        ),
        200,
    )


@location_blueprint.route("/", methods=["GET"])
@login_required
def all_locations_list():
    """Returns all locations (id and name) as JSON

    Returns:
        JSON: all locations list
    """
    # If user has global access return all locations
    match current_user.permission:
        case m.UserPermissionLevel.GLOBAL:
            locations = m.Location.query.order_by(m.Location.name).all()
        case m.UserPermissionLevel.COMPANY:
            locations = (
                m.Location.query.filter_by(company_id=current_user.company_id)
                .order_by(m.Location.name)
                .all()
            )
        case m.UserPermissionLevel.LOCATION_GROUP:
            locations = (
                m.Location.query.filter(
                    m.Location.id.in_(
                        [
                            location.id
                            for location in current_user.location_group[0].locations
                        ]
                    )
                )
                .order_by(m.Location.name)
                .all()
            )
        case m.UserPermissionLevel.LOCATION:
            locations = m.Location.query.filter_by(id=current_user.location[0].id).all()
        case _:
            locations = []

    res = [(location.id, location.name) for location in locations]

    return jsonify(locations=res), 200


@location_blueprint.route("/<int:computer_id>/additional_locations", methods=["GET"])
@login_required
def computer_additional_locations(computer_id: int):
    """Returns if computer has additional locations

    Args:
        computer_id (int): computer id

    """
    computer: m.Computer = m.Computer.query.filter_by(id=computer_id).first()

    if not computer:
        logger.error("Computer with id [{}] not found", computer_id)
        abort(404, "Computer not found.")

    logger.info("Sending data of compiter {}", computer.computer_name)
    return (
        jsonify(
            additional_locations=[
                loc.location_id for loc in computer.additional_locations
            ],
        ),
        200,
    )

web/app/templates/info/company.html
{% extends "base.html" %}
<!-- prettier-ignore -->
{% block flash_messages %} {% endblock %}
<!-- prettier-ignore -->
{% block content %}
<div class="d-flex flex-column justify-content-center w-100">
  <!-- "Go back" button -->
  <!-- prettier-ignore -->
  <div class="d-flex w-100 mb-4">
    <!-- prettier-ignore -->
    <a class="text-decoration-none small" href="{{ url_for('company.index_view')}}" > <i class="fas fa-arrow-left"></i> Go back </a>
        <a
      type="button"
      href="/admin/company/edit/?id={{ company.id }}"
      class="btn btn-default btn-primary ml-auto mr-2"
      >Edit</a
    >
  </div>
  <!-- End "Go back" button -->

  <!-- Locations online and offline block -->
  <div class="row">
    <!-- Locations Offline Card -->
    <div class="col mb-4">
      <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div
                class="text-xxs font-weight-bold text-danger text-uppercase mb-1"
              >
                <p class="dash-cards">Locations Offline</p>
              </div>
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <div class="h3 mb-0 mr-3 font-weight-bold text-gray-800">
                    {{company.total_offline_locations}}
                  </div>
                </div>
                <div class="col">
                  <div class="col">
                    <div class="progress progress-sm mr-2">
                      {% if company.total_online_locations > 0 %}
                      <div
                        class="progress-bar bg-danger"
                        role="progressbar"
                            style="width: {{ (company.total_offline_locations / (company.locations|length)) * 100 }}%"
                        aria-valuenow="50"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                      {% else %}
                      <div
                        class="progress-bar bg-danger"
                        role="progressbar"
                        style="width: 0%"
                        aria-valuenow="50"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-auto align-items-center">
              <div class="row no-gutters h5">
                <i
                  class="fas fa-map-marker-alt fa-1x text-danger center-hor"
                ></i>
              </div>
              <div class="row no-gutters h5">
                <i class="fas fa-power-off fa-1x text-danger center-hor"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Row 2: locations online; locations alternate only -->
  <div class="row">
    <!-- Locations online -->
    <div class="col mb-4">
      <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div
                class="text-xxs font-weight-bold text-success text-uppercase mb-1"
              >
                <p class="dash-cards">Locations Online</p>
              </div>
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <div class="h3 mb-0 mr-3 font-weight-bold text-gray-800">
                    {{ company.total_online_locations }}
                  </div>
                </div>
                <div class="col">
                  <div class="col">
                    <div class="progress progress-sm mr-2">
                       {% if company.total_online_locations > 0 %}
                      <div
                        class="progress-bar bg-danger"
                        role="progressbar"
                            style="width: {{ (company.total_offline_locations / (company.locations|length)) * 100 }}%"
                        aria-valuenow="50"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                      {% else %}
                      <div
                        class="progress-bar bg-danger"
                        role="progressbar"
                        style="width: 0%"
                        aria-valuenow="50"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-auto align-items-center">
              <div class="row no-gutters h5">
                <i
                  class="fas fa-map-marker-alt fa-1x text-success center-hor"
                ></i>
              </div>
              <div class="row no-gutters h5">
                <i class="fas fa-power-off fa-1x text-success center-hor"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End of online and offline locations -->
  <!-- Location info -->
  <div class="d-flex w-100 p-4">
    <div class="d-flex w-50 flex-column justify-content-center m-3">
      <div class="d-flex flex-column justify-content-start">
        <span class="text-grey mb-1 small text-center">Company</span>
        <span class="mb-3 small text-dark text-center">{{ company.name }}</span>
      </div>

      <div class="d-flex flex-column justify-content-start">
        <span class="text-grey mb-1 small text-center">Sftp UserName</span>
        <span class="mb-3 small text-dark text-center"
          >{{ company.default_sftp_username}}</span
        >
      </div>
      <div class="d-flex flex-column justify-content-start">
        <span class="text-grey mb-1 small text-center">Sftp Password</span>
        <span class="mb-3 small text-dark text-center"
          >{{ company.default_sftp_password}}</span
        >
      </div>

      <div class="d-flex flex-column justify-content-start">
        <span class="text-grey mb-1 small text-center">PCC Org ID</span>
        <span class="mb-3 small text-dark text-center"
          >{{ company.pcc_org_id }}</span
        >
      </div>
    </div>
    <div class="d-flex w-50 flex-column justify-content-center m-3">
            <div class="d-flex flex-column justify-content-start">
        <span class="text-grey mb-1 small text-center">Computers online</span>
        <span class="mb-3 small text-dark text-center"
          >{{ company.computers_online }}</span
        >
      </div>

      <div class="d-flex flex-column justify-content-start">
        <span class="text-grey mb-1 small text-center">Computers offline</span>
        <span class="mb-3 small text-dark text-center"
          >{{ company.computers_offline }}</span
        >
      </div>
    </div>
  </div>
  <!-- End location info -->

  {% for loc in company.locations %}
  <p>{{loc.name}}</p>
    {% if not loc.computers %}
      <div class="text-grey mb-2 d-flex justify-content-center">
      No computers in this location
    </div>
    {% else %}
  <div
    class="d-flex w-100 p-4 justify-content-center flex-column align-items-center"
  >
    <div class="text-grey mb-2 d-flex justify-content-center">
      Computers in this location
    </div>
    <div class="w-100">
      <div>
        <table
          class="w-full text-xs text-center table table-striped table-bordered table-hover pr-2 pl-2"
        >
          <thead class="text-sm text-center" style="color: #4e73df">
            <tr>
              <th scope="col">Device Name</th>
              <th scope="col" class="pr-2 pl-2">Status</th>
              <th scope="col">Role</th>
              <th scope="col">Type</th>
              <th scope="col">Last download time</th>
              <th scope="col">Last time online</th>
            </tr>
          </thead>
          <tbody>
            {% for computer in loc.computers %}
            <tr>
              <td class="p-2 text-gray align-middle">
               <a href="{{url_for('info.computer_info', computer_id=computer.id)}}">
                <div>{{ computer.computer_name }}</div></a>
              </td>
              {% if computer.status.value == "ONLINE" %}
              <td
                class="p-2 text-dark align-middle"
                style="background-color: #1cc88a"
              >
                <div>"ONLINE"</div>
              </td>
              {% elif computer.status.value == "ONLINE_NO_BACKUP" %}
              <td
                class="p-2 text-dark align-middle"
                style="background-color: #f6c23e"
              >
                <div>"ONLINE_NO_BACKUP"</div>
              </td>
              {% elif computer.status.value == "OFFLINE_NO_BACKUP" %}
              <td
                class="p-2 text-white align-middle"
                style="background-color: #e74a3b"
              >
                <div>"OFFLINE_NO_BACKUP"</div>
              </td>
              {% elif computer.status.value == "NOT_ACTIVATED" %}
              <td
                class="p-2 text-white align-middle"
                style="background-color: #848383"
              >
                <div>"NOT_ACTIVATED"</div>
              </td>
              {% endif %}
              <td class="p-2 text-gray align-middle">
                <span>{{ computer.device_role.value }}</span>
              </td>
              <td class="p-2 text-gray align-middle">
                <span>{{ computer.device_type.value }}</span>
              </td>
              <td class="p-2 text-gray align-middle">
                <div>{{ computer.last_download_time }}</div>
              </td>
              <td class="p-2 text-gray align-middle">
                <div>{{ computer.last_time_online }}</div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock %} {% block sidebar_toggle %}
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      $("#sidebarToggle").click();
    });
  </script>
  {% endblock sidebar_toggle %} {% block bootstrap_core %}
  <!-- This if statement is required to avoid double import if jQuery. Otherwise some functions brake -->
  <script src="{{ url_for('static', filename='/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='/vendor/jquery/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='/vendor/jquery/popper.min.js.map') }}"></script>
  {% endblock bootstrap_core %}
</div>